config/routes.rb
Rails.application.routes.draw do
  devise_for :artists
  resources :artworks

  root 'overview#showcase'
  get 'showcase' => 'overview#showcase'
  get 'artist/:id' => 'artists#show'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :artworks

  def fullname
  	"#{first_name} #{last_name}"
  end

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :artist

  has_attached_file :image, :styles => {
    :square => "250x250#",
    :medium => "500x500>",
    :thumb => "250x250#"
  },:default_url => "/images/:style/missing.png"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates_with AttachmentSizeValidator, :attributes => :image, :less_than => 10.megabytes

  def image_url
    image.url(:medium)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #before_action :authenticate_artist!, :except => [:showcase]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, 
    :password_confirmation, :first_name, :last_name, :zip) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, 
   :password_confirmation, :current_password, :first_name, :last_name, :zip) }
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def show
    @artist = Artist.find(params[:id])
  end

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]

  # GET /artworks
  # GET /artworks.json
  def index
    @artworks = Artwork.all
    @artists = Artist.all
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
    @artworks = Artwork.find_by_id(current_artist.id)
  end

  # POST /artworks
  # POST /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.artist_id = current_artist.id
    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Artwork was successfully created.' }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1
  # PATCH/PUT /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: 'Artwork was successfully updated.' }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url, notice: 'Artwork was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artwork_params
      params.require(:artwork).permit(:artist_id, :title, :media, :price, :image)
    end
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  def home
  end

  def showcase
  	@artists = Artist.all
  	@artworks = Artwork.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/overview_helper.rb
module OverviewHelper
end

app/views/artists/show.html.erb
<%= @artist.fullname %>

<% @artist.artworks.each do |artwork| %>
  <%= image_tag artwork.image.url(:thumb), alt: artwork.title %>
<% end %>

app/views/artworks/_artist_profile.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p class="lead"><%= @artwork.artist.fullname %></p>
    <p>
      Cookie cotton candy candy canes bear claw cookie jelly-o dragée carrot cake lollipop. Cookie pudding danish ice cream jelly beans chocolate bar jelly wafer bear claw. Dragée lollipop chupa chups. Bonbon croissant muffin. Cupcake muffin chocolate bar chocolate. Cake powder sugar plum bonbon soufflé. Chocolate bar sugar plum oat cake. Apple pie fruitcake toffee biscuit cupcake muffin. Cheesecake soufflé cheesecake sugar plum pie soufflé cupcake icing. Toffee oat cake bonbon. Pastry carrot cake sweet. Pie lemon drops cake wafer chupa chups.
    </p>
    <div style="padding-top:20px;white-space:nowrap;overflow-x:hidden;text-overflow: ellipsis;">
      <% counter = 0 %>
        <% @artwork.artist.artworks.each do |artwork| %>
          <% counter += 1 %>
          <% if counter < 10 %>
            <a href="/artworks/<%= artwork.id %>">
              <%= image_tag artwork.image.url(:thumb), size: "100x100", alt: artwork.title, class: 'img-rounded' %>
            </a>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/artworks/_form.html.erb
<%= form_for(@artwork) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= f.label :artist %><br>
    <%#= f.number_field :artist_id %>
    <%#= f.select(:artist_id, @artists.collect {|a| [ a.fullname, a.id ] }, {:include_blank => 
      'Please select an item'}) %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :media %><br>
    <%= f.text_field :media %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Editing Artwork</h1>
<%= @artistid %>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

app/views/artworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artworks</h1>

<div class="responsive-table">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Artist</th>
      <th>Title</th>
      <th>Media</th>
      <th>Price</th>
      <th>ArtWork</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artworks.each do |artwork| %>
      <tr>
        <td><%= artwork.artist.fullname %></td>
        <td><%= artwork.title %></td>
        <td><%= artwork.media %></td>
        <td><%= number_to_currency(artwork.price) %></td>
        <% if artwork.image_file_name != nil %>
              <td><%= image_tag artwork.image.url(:thumb) %></td>
        <% end %>
        <td><%= link_to 'Show', artwork %></td>
        <td><%= link_to 'Edit', edit_artwork_path(artwork) %></td>
        <td><%= link_to 'Destroy', artwork, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div><!-- end of responsive table -->

<br>

<%= link_to 'New Artwork', new_artwork_path %>

app/views/artworks/new.html.erb
<h1>New Artwork</h1>

<%= render 'form' %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col-md-6 col-md-push-6">
    <p>
      <%= image_tag @artwork.image.url(:medium), class: 'img-frame img-reponsive img-thumbnail' %>
    </p>
    <div class="pull-left">
      <p class="artwork-lead">
        <%= @artwork.title %>
      </p>

      <p>
        <%= @artwork.media %>
      </p>
    </div>
    <div class="pull-right">
      <p class="artwork-lead">
        <%= number_to_currency(@artwork.price) %>
      </p>
      <p>
        <% if signed_in? && current_artist == @artwork.artist %>
          <small><%= link_to 'Edit', edit_artwork_path(@artwork) %></small>
        <% end %>
      </p>
    </div>
  </div>

  <div class="col-md-6 col-md-pull-6">
    <%= render 'artist_profile' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Localist</title>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Indie+Flower|Pacifico|Oswald' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Localist</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Artworks", artworks_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if artist_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  <%= current_artist.first_name %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Edit Account", edit_artist_registration_path%></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign Out", destroy_artist_session_path, method: :delete%></li>
                 </ul>
              </li>
            <% else %>
              <li><%= link_to "Become a Member", new_artist_registration_path%></li>
              <li><%= link_to "Sign In", new_artist_session_path%></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
    	
      <%= yield %>

    </div>
  </body>
</html>

app/views/overview/home.html.erb
<h1>The home page if we need one.</h1>

app/views/overview/showcase.html.erb
<ul id="og-grid" class="og-grid showcase-gallery">
  <% @artworks.each do |artwork| %>
    <% if artwork.image_file_name.present? %>
      <li>
        <a href="/artworks/<%= artwork.id %>" data-largesrc="<%= artwork.image.url(:medium) %>" data-title="<%= artwork.title %>" data-description="" data-artist="<%= artwork.artist.fullname %>" data-media="<%= artwork.media %>" data-price="<%= number_to_currency(artwork.price) %>">
          <%= image_tag artwork.image.url(:thumb), alt: artwork.title %>
        </a>
      </li>
    <% end %>
  <% end %>
</ul>
<script src="https://s3.amazonaws.com/localist-art/grid.js"></script>
<script>
  $(function() {
    Grid.init();
  });
</script>